//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.16.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "contactFormControls"
	/// <summary>Contact Form Controls</summary>
	public partial interface IContactFormControls : IPublishedContent
	{
		/// <summary>ErrorMessageP</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		global::System.Web.IHtmlString ErrorMessageP { get; }

		/// <summary>SuccesMessageP</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		global::System.Web.IHtmlString SuccesMessageP { get; }
	}

	/// <summary>Contact Form Controls</summary>
	[PublishedModel("contactFormControls")]
	public partial class ContactFormControls : PublishedContentModel, IContactFormControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public new const string ModelTypeAlias = "contactFormControls";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactFormControls, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ContactFormControls(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// ErrorMessageP: Aqui va el mensaje en caso de error.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("errorMessageP")]
		public virtual global::System.Web.IHtmlString ErrorMessageP => GetErrorMessageP(this);

		/// <summary>Static getter for ErrorMessageP</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public static global::System.Web.IHtmlString GetErrorMessageP(IContactFormControls that) => that.Value<global::System.Web.IHtmlString>("errorMessageP");

		///<summary>
		/// SuccesMessageP: Aqui va el mensaje en caso de exito.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("succesMessageP")]
		public virtual global::System.Web.IHtmlString SuccesMessageP => GetSuccesMessageP(this);

		/// <summary>Static getter for SuccesMessageP</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public static global::System.Web.IHtmlString GetSuccesMessageP(IContactFormControls that) => that.Value<global::System.Web.IHtmlString>("succesMessageP");
	}
}
