//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.16.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel, IContentControls, IFooterControls, IHeaderControls, IMainImageControls, ISEocontrols
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Home(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// ContentP
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("contentP")]
		public virtual global::Newtonsoft.Json.Linq.JToken ContentP => global::Umbraco.Web.PublishedModels.ContentControls.GetContentP(this);

		///<summary>
		/// SocialLinksP: Aqui va los links social media para el footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("socialLinksP")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.IconLinkItem> SocialLinksP => global::Umbraco.Web.PublishedModels.FooterControls.GetSocialLinksP(this);

		///<summary>
		/// SubtitleP: Aqui va el subtitulo de la pagina.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("subtitleP")]
		public virtual string SubtitleP => global::Umbraco.Web.PublishedModels.HeaderControls.GetSubtitleP(this);

		///<summary>
		/// TitleP: Aqui va el titulo de de la pagina. Si no hay titulo, el nombre de la pagina sera el que aparezca como titulo.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("titleP")]
		public virtual string TitleP => global::Umbraco.Web.PublishedModels.HeaderControls.GetTitleP(this);

		///<summary>
		/// MainImageP: Aqui va la imagen principal de la pagina.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("mainImageP")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops MainImageP => global::Umbraco.Web.PublishedModels.MainImageControls.GetMainImageP(this);

		///<summary>
		/// MetaDescriptionP: Aqui va la meta description para esta pagina.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("metaDescriptionP")]
		public virtual string MetaDescriptionP => global::Umbraco.Web.PublishedModels.SEocontrols.GetMetaDescriptionP(this);

		///<summary>
		/// MetaKeysP: Aqui van las meta keys para esta pagina.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("metaKeysP")]
		public virtual global::System.Collections.Generic.IEnumerable<string> MetaKeysP => global::Umbraco.Web.PublishedModels.SEocontrols.GetMetaKeysP(this);

		///<summary>
		/// MetaNameP: Aqui va el meta name para esta pagina.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.16.0")]
		[ImplementPropertyType("metaNameP")]
		public virtual string MetaNameP => global::Umbraco.Web.PublishedModels.SEocontrols.GetMetaNameP(this);
	}
}
